[package]
name = "order-book"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
colored = "3.0.0"
rust_decimal = "1.37.2"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
